# ---------------------------------------------------------------------------
#  Config adicional del agente "srv-db"  (endurecido)
# ---------------------------------------------------------------------------

DenyKey=system.run[*]

# --- UserParameters SEGUROS orientados a "base de datos" -------------------
# Uso de memoria disponible en KB (proxy de presión de memoria del host BD).
UserParameter=db.mem.available,awk '/MemAvailable/ {print $2}' /proc/meminfo

# Carga del sistema a 1 minuto.
UserParameter=db.load.avg1,awk '{print $1}' /proc/loadavg

# Nº de ficheros abiertos a nivel de kernel (indicador de fugas de descriptores).
UserParameter=db.fd.open,awk '{print $1}' /proc/sys/fs/file-nr
